# Generated by Django 2.2.4 on 2019-09-03 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotames', models.CharField(max_length=5)),
                ('multa1', models.IntegerField(blank=True, null=True)),
                ('multa2', models.IntegerField(blank=True, null=True)),
                ('cuota1', models.IntegerField(blank=True, null=True)),
                ('cuota2', models.IntegerField(blank=True, null=True)),
                ('fechapub', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('numsocio', models.CharField(max_length=15, null=True)),
                ('nombre1', models.CharField(max_length=15)),
                ('nombre2', models.CharField(max_length=15, null=True)),
                ('apellido1', models.CharField(max_length=15)),
                ('apellido2', models.CharField(max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No_declarado')], max_length=1)),
                ('direccion', models.CharField(max_length=60, null=True)),
                ('comuna', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('cumple', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_socios')),
                ('valoracion', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechapago', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadocuota', models.BooleanField(choices=[(True, 'Pagado'), (False, 'Adeudado')], default='Adeudado')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_sociales', to='pagos.Cuota')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
