# Generated by Django 2.2.4 on 2019-09-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20190903_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='cuotames',
            new_name='cuota',
        ),
    ]
