# Generated by Django 2.2.4 on 2019-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20190903_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fechapago',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
