# Generated by Django 2.2.4 on 2019-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20190903_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fechapago',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
